cache:
  directories:
  - $HOME/.jdk
sudo: false
env:
  global:
  - JDKW_VERSION=8u65
  - JDKW_BUILD=b17
install: true
script:
- ./jdk-wrapper.sh javac -version
- if [ ! -d "/home/travis/.jdk/8u65_b17_linux-i586/jdk1.8.0_65" ]; then exit 1; fi;
