cache:
  directories:
  - $HOME/.jdk
sudo: false
env:
  - JDKW_VERSION=8u74 JDKW_BUILD=b02
install: true
script:
- ./jdk-wrapper.sh javac -version
- if [ "$(./jdk-wrapper.sh javac -version 2>&1 | tail -n 1)" != "javac 1.8.0_74" ]; then exit 1; fi;
