cache:
  directories:
  - $HOME/.jdk
sudo: false
env:
  global:
  - JDKW_VERSION=8u65
  - JDKW_BUILD=b17
install: true
script:
- ./jdk-wrapper.sh javac -version
- if [ "$(./jdk-wrapper.sh javac -version 2>&1 | tail -n 1)" != "javac 1.8.0_65" ]; then exit 1; fi;
