cache:
  directories:
  - $HOME/.jdk
sudo: false
env:
  global:
  - JDKW_VERSION=8u65
  - JDKW_BUILD=17
script:
- if [ "$(./jdk-wrapper.sh javac -version 2>&1)" != "javac 1.8.0_65" ]; then exit 1; fi;
